### ISSUE TITLE
Deploy directly to Github Pages through Github Actions

### ISSUE THREAD

**Issue by rollerozxa** [minetest/benchmarks#5]
Currently it deploys to Github Pages through pushing commits to the gh-pages branch. This isn't necessary anymore since you can directly deploy a directory to Github Pages from Github Actions, reducing the amount of repository size churn that will happen when it commits automatically generated content into the repository.

The `pages: write` permission will need to be added to the top of the YAML, and then to deploy directly to Github pages the following steps would do that:

```yaml
      - name: Setup Pages
        if: ${{ env.DID_PUSH == 'true' }}
        uses: actions/configure-pages@v4

      - name: Upload artifact
        if: ${{ env.DID_PUSH == 'true' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'principia/doc/doxy/html/'

      - name: Deploy to GitHub Pages
        if: ${{ env.DID_PUSH == 'true' }}
        id: deployment
        uses: actions/deploy-pages@v4
```

[Repository settings](https://github.com/luanti-org/benchmarks/settings/pages) will also need to be changed to match.

![Image](https://github.com/user-attachments/assets/dcb244b7-e444-4ae8-a749-b37e2745af26)
